### ISSUE TITLE
Using the ESP32 as NAT gateway

### ISSUE THREAD

**Issue by amotl** [ISEMS/ISEMS-ESP32#10]
Dear Elektra,

as I heard about your plans to co-use the ESP32 not only for controlling the MPPT charger, but also as an IP router, I initially doubted if this would work reliably.

However, I just discovered [esp32_nat_router](https://github.com/martin-ger/esp32_nat_router) by @martin-ger and contributors, so it looks like this plan might actually be feasible. You might be interested about their project over there, so I thought it would be a good idea to drop you a note about it.

With kind regards,
Andreas.

P.S.: As this is more a note than an actual issue, you might want to close it right away or move it to the "discussions" section.

**Comment by elektra42** [comment]
Hi Andreas  –

the OpenMPPT firmware supports IPv4 based routing and adding routes to a routing table, thanks to @dh1df: https://github.com/dh1df/ESPTREE-Testbed 

The maxiumum number of entries can be configured when compiling the firmware. There is also experimental Lua code for ESPTree. ESPTree is an experimental routing and IP autoconfiguration tool in Lua that can set up a spanning tree IPv4 network including up to 220 OpenMPPT nodes with an OpenWRT device as the tree root node/LAN or WAN gateway.

Since the OpenMPPT lacks a WAN interface, IMO it doesn't make sense to do NAT in the OpenMPPT unless you want to connect to a remote WAN gateway that you can not control. Which will often be the case in a travelling situation. But this is not the scope of the OpenMPPT project.

For a network segment consisting of ESP32 WiFi nodes I suggest to not do NAT in the ESP nodes to solve IPv4 routing problems or to work around the routing limitations of the unpatched embedded IP stack. As long as one can set up an IPv4 route at the WAN gateway into the network segment of ESP32s, one doesn't need NAT. If one can't do that, NAT can come to the rescue to get a somehow 'broken' network running with two or more instances of NAT in series. 'Broken' because the communication can only initiated from one direction and it is also slowed down due to the overhead.

IPv4 forwarding performance of the OpenMPPT device is on par at 240 MHz ESP32 clock frequency with a small OpenWRT based pocket router WR802n at 40 MHz WiFi channel bandwidth and a small routing table. I achieved arount 6.3 MByte/s per WiFi link.

**Comment by amotl** [comment]
Hi again,

I just discovered https://github.com/david-cermak/eth-ap-nat by @david-cermak, and wanted to share it here, because it may also be of interest to you.

With kind regards,
Andreas.

**Comment by elektra42** [comment]
Hi Andreas!

Thanks for sharing!

I'm trying to avoid NAT'ing wherever I can ;)

We have IP-based routing support in the ISEMS firmware. So we can build networks by adding and removing routes. With regards to networking, stability and performance this is the way to go, unless we absolutely have to run a device as a gateway into a WAN. I would use an OpenWRT based device for that any day. 

NAT requires connection tracking and cascading NAT instances is a no-go. With more than wee bit of traffic you'll run into issues. Even standard WiFi routers with way larger sizes of RAM crash because of too many connections. The workaround is to cut down the connection tracking time. 

NAT is of limited use for the OpenMPPT, since it doesn't have a LAN port. It might come handy if you want to use an ESP32 board for something like a travel router, that relays traffic using the software AP plus client option of the ESP: It connects to a WiFi hotspot as a client that you can not configure yourself (or the friendly admin) to set up proper routing to avoid NAT to the network of the ESPs SoftAP-Interface.

Using NAT in this situation is slow and unstable, but it might help in a pinch.

However, if I install an OpenMPPT system somewhere, I'll set up an OpenWRT based gateway.



Am 30. Mai 2023 23:04:54 MESZ schrieb Andreas Motl ***@***.***>:
